config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :cart_items, only: [:update]
  resources :order_items
  resources :orders
  resource :cart, only: [:show]

  resources :carts do
    delete 'cart_items/:cart_item_id', to: 'carts#destroy_item', on: :member, as: :delete_item
  end

  resources :items
  devise_for :users
 
  resources :users, :paths => 'users'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  resources :quotes, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :mark, action: :mark
      post :reprocess
    end
  end

  scope '/dashboard' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/users', to: 'dashboard#users', as: 'dashboard_users'
    get '/quotes', to: 'dashboard#quotes', as: 'dashboard_quotes'
    get '/store', to: 'dashboard#store', as: 'dashboard_store'
    post '/create', to: 'dashboard#create', as: 'dashboard_create'
    get '/products', to: 'dashboard#products', as: 'dashboard_products'
    get '/orders', to: 'dashboard#orders', as: 'dashboard_orders'
  end


  
  resources :orders, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  get 'welcome_email', to: 'welcome_mailer#welcome_email'
  get '/portfolio', to: 'portfolio#show', as: 'portfolio'
  get '/devis', to: 'quotes#new', as: 'devis'
  get 'faq', to: 'faq#index', as: 'faq'
  get '/mentions-legales', to: 'legal_notices#index', as: 'legal_notices'
  get '/politique-de-confidentialite', to: 'privacy_policy#index', as: 'privacy_policy'
  get '/politique-de-remboursement', to: 'refund_policy#index', as: 'refund_policy'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
    #Ici on créer les fonctions qui permettent dêtre appeler dans le Dashbord admin et...
    #...l'intéragir avec les views le .cont permet de regrouper en comptant
    @num_users = User.count
    @num_quotes = Quote.count
    @num_orders = Order.count
    @recent_orders = Order.where(created_at: (Time.now - 24.hours)..Time.now).order(created_at: :desc)
    @users = User.where('created_at >= ?', 24.hours.ago).order(created_at: :desc)
    @orders = Order.all
    @order_count = Order.count
    @num_items = Item.count
    #gestion de devis traité et non traité
    @processed_quotes = Quote.where(processed: true)
    @unprocessed_quotes = Quote.where(processed: false)
    
  end
  
  def show
    # Vous pouvez ajouter ici la logique de gestion de la page d'accueil du tableau de bord.
    # Par exemple, récupérer des données de la base de données.
  end
  
  def store
    @item = Item.new
  end
  
  def orders
    start_date = params[:start_date]
    end_date = params[:end_date]
    
    
    @orders = Order.where(created_at: start_date..end_date)
  end
  
  
  def products
    @items = Item.all
  end
  
  def quotes
    @quotes = Quote.all
    @unprocessed_quotes = Quote.where(processed: false)
    @processed_quotes = Quote.where(processed: true)
    render 'dashboard/quotes'
  end
  
  
  def users
    @users = User.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to dashboard_store_path, notice: "Le produit a été ajouté avec succès."
    else
      render 'store'
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:title, :description, :price, :image_url, :alt, :category)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<section class="antialiased bg-black w-full min-h-screen text-slate-300 relative py-4">
  <div class="grid grid-cols-12 mx-auto gap-2 sm:gap-4 md:gap-6 lg:gap-10 xl:gap-14 max-w-7xl my-10 px-2">
    <article id="menu" class="bg-white/10 col-span-3 rounded-lg p-4">
      <h1 class="font-bold text-lg lg:text-3xl bg-gradient-to-br from-white via-white/50 to-transparent bg-clip-text text-transparent">
        Dashboard<span class="text-indigo-400">.</span>
      </h1>
      <p class="text-slate-400 text-sm mb-2">Admin,</p>
      <hr class="my-2 border-slate-700">
      <div id="menu" class="flex flex-col space-y-2 my-5">
        <a href="#" class="hover:bg-white/10 transition duration-150 ease-linear rounded-lg py-3 px-2">
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 space-x-2 items-center">
            <div>
              <i class="fa-solid fa-house text-2xl"></i>
            </div>
            <div>
              <p class="font-bold text-xl lg:text-lg text-slate-200 leading-4 group-hover:text-indigo-400">Dashboard</p>
              <p class="text-slate-400 text-sm hidden md:block">Data général et 24H</p>
            </div>
          </div>
        </a>
        <a href="<%= dashboard_orders_path %>" class="hover:bg-white/10 transition duration-150 ease-linear rounded-lg py-3 px-2">
          <div class="relative flex flex-col space-y-2 md:flex-row md:space-y-0 space-x-2 items-center">
            <div>
              <i class="fa-solid fa-bag-shopping text-2xl"></i>
            </div>
            <div>
              <p class="font-bold text-base lg:text-lg text-slate-200 leading-4 group-hover:text-indigo-400">Commandes</p>
              <p class="text-slate-400 text-sm hidden md:block">Liste des commandes</p>
            </div>
          </div>
        </a>
        <a href="<%= dashboard_users_path %>" class="hover:bg-white/10 transition duration-150 ease-linear rounded-lg py-3 px-2">
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 space-x-2 items-center">
            <div>
              <i class="fa-solid fa-user-group text-2xl"></i>
            </div>
            <div>
              <p class="font-bold text-xl lg:text-lg text-slate-200 leading-4 group-hover:text-indigo-400">Utilisateurs</p>
              <p class="text-slate-400 text-sm hidden md:block">Liste des utilisateurs</p>
            </div>
          </div>
        </a>
        <a href="<%= dashboard_quotes_path %>" class="hover:bg-white/10 transition duration-150 ease-linear rounded-lg py-3 px-2">
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 space-x-2 items-center">
            <div>
              <i class="fa-solid fa-file-contract text-2xl"></i>
            </div>
            <div>
              <p class="font-bold text-xl lg:text-lg text-slate-200 leading-4 group-hover:text-indigo-400">Devis</p>
              <p class="text-slate-400 text-sm hidden md:block">Gérer les Devis</p>
            </div>
          </div>
        </a>
        <a href="<%= dashboard_products_path %>" class="hover:bg-white/10 transition duration-150 ease-linear rounded-lg py-3 px-2">
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 space-x-2 items-center">
            <div>
              <i class="fa-solid fa-shop text-2xl"></i>
            </div>
            <div>
              <p class="font-bold text-base lg:text-lg text-slate-200 leading-4 group-hover:text-indigo-400">Boutique</p>
              <p class="text-slate-400 text-sm hidden md:block">Liste des produits en boutique</p>
            </div>
          </div>
        </a>
        <a href="<%= dashboard_store_path %>" class="hover:bg-white/10 transition duration-150 ease-linear rounded-lg py-3 px-2">
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 space-x-2 items-center">
            <div>
              <i class="fa-solid fa-plus text-2xl"></i>
            </div>
            <div>
              <p class="font-bold text-xl lg:text-lg text-slate-200 leading-4 group-hover:text-indigo-400">Produits</p>
              <p class="text-slate-400 text-sm hidden md:block">Ajouts produits boutique</p>
            </div>
          </div>
        </a>
      </div>
      <p class="text-sm text-center text-gray-600">Dashboard | &copy; 2023 Rustoff</p>
    </article>
    <article id="content" class="bg-white/10 col-span-9 rounded-lg p-6">
      <div id="24h">
        <h1 class="font-bold py-4 uppercase">Statistiques</h1>
        <div id="stats" class="grid gird-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div class="bg-black/60 to-white/5 p-6 rounded-lg">
            <div class="flex flex-row space-x-4 items-center">
              <div id="stats-1">
                <i class="fa-solid fa-users text-4xl text-white"></i>
              </div>
              <div>
                <p class="text-indigo-300 text-sm font-medium uppercase leading-4">Utilisateurs</p>
                <p class="text-white font-bold text-2xl inline-flex items-center space-x-2">
                  <span><%= @num_users %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="bg-black/60 p-6 rounded-lg">
            <div class="flex flex-row space-x-4 items-center">
              <div id="stats-1">
                <i class="fa-solid fa-file-invoice-dollar text-4xl text-white"></i>
              </div>
              <div>
                <p class="text-teal-300 text-sm font-medium uppercase leading-4">Devis</p>
                <p class="text-white font-bold text-2xl inline-flex items-center space-x-2">
                  <span><%= @num_quotes %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="bg-black/60 p-6 rounded-lg">
            <div class="flex flex-row space-x-4 items-center">
              <div id="stats-1">
                <i class="fa-solid fa-file-circle-check text-4xl text-white"></i>
              </div>
              <div>
                <p class="text-green-300 text-sm font-medium uppercase leading-4">Devis Traité</p>
                <p class="text-white font-bold text-2xl inline-flex items-center space-x-2">
                  <span><%= @processed_quotes.count %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="bg-black/60 p-6 rounded-lg">
            <div class="flex flex-row space-x-4 items-center">
              <div id="stats-1">
                <i class="fa-solid fa-file-circle-xmark text-4xl text-white"></i>
              </div>
              <div>
                <p class="text-purple-300 text-sm font-medium uppercase leading-4">Devis Non-Traité</p>
                <p class="text-white font-bold text-2xl inline-flex items-center space-x-2">
                  <span><%= @unprocessed_quotes.count %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="bg-black/60 p-6 rounded-lg">
            <div class="flex flex-row space-x-4 items-center">
              <div id="stats-1">
                <i class="fa-solid fa-euro-sign text-4xl text-white"></i>
              </div>
              <div>
                <p class="text-blue-300 text-sm font-medium uppercase leading-4">Commandes</p>
                <p class="text-white font-bold text-2xl inline-flex items-center space-x-2">
                  <span><%= @num_orders %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="bg-black/60 p-6 rounded-lg">
            <div class="flex flex-row space-x-4 items-center">
              <div id="stats-1">
                <i class="fa-regular fa-images text-4xl text-white"></i>
              </div>
              <div>
                <p class="text-rose-300 text-sm font-medium uppercase leading-4">Articles en Boutique</p>
                <p class="text-white font-bold text-2xl inline-flex items-center space-x-2">
                  <span><%= @num_items %></span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="last-incomes">
        <h1 class="font-bold py-4 uppercase">Commandes dernières 24H</h1>
        <div id="stats" style="max-width: 600px;">
          <% @recent_orders.each do |order| %>
            <div class="bg-black/60 to-white/5 rounded-lg" style="display: inline-block; width: auto; margin: 10px;">
              <div class="flex flex-row items-center">
                <div class="text-3xl p-4">💰</div>
                <div class="p-2">
                  <p class="text-xl font-bold"><%= number_to_currency(order.total_price, unit: '€') %></p>
                  <p class="text-gray-500 font-medium"><%= order.user.email %></p>
                  <p class="text-gray-500 text-sm"><%= order.created_at.strftime("%d %b %Y") %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div id="last-users">
        <h1 class="font-bold py-4 uppercase">Utilisateurs inscrits dernières 24H</h1>
        <div class="overflow-x-scroll">
          <table class="w-full whitespace-nowrap">
            <thead class="bg-black/60">
              <th class="text-left py-3 px-2">Email</th>
              <th class="text-left py-3 px-2">Group</th>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr class="border-b border-gray-700">
                  <td class="py-3 px-2"><%= user.email %></td>
                  <td class="py-3 px-2"><%= user.admin ? 'Administrator' : 'User' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/dashboard/orders.html.erb
<section class="container mx-auto text-black p-4 w-full">
  <div class="flex items-center justify-center mt-10 w-full">
    <h1 class="text-4xl font-bold p-4 border-4 border-gray-500 rounded inline-block mb-10">Liste des commandes :</h1>
  </div>
  <article class="mt-6 text-center mb-10 w-full">
    <%= form_tag dashboard_orders_path, method: :get, class: "mb-4 w-full" do %>
      <label for="start_date" class="text-black font-semibold">Date de début :</label>
      <%= text_field_tag "start_date", params[:start_date], class: "border rounded p-2 datepicker", data: { format: "DD/MM/YYYY" }, autocomplete: "off" %>

      <label for="end_date" class="text-black font-semibold ml-4">Date de fin :</label>
      <%= text_field_tag "end_date", params[:end_date], class: "border rounded p-2 datepicker2", data: { format: "DD/MM/YYYY" }, autocomplete: "off" %>

      <%= submit_tag "Rechercher", class: "bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline ml-4" %>
    <% end %>
  </article>
  <article class="overflow-x-auto w-full">
    <table class="min-w-full bg-gray-800 border text-white rounded-lg">
      <thead>
        <tr>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">ID de la Commande</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Utilisateur</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Prix Total</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Date de la Commande</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Articles commandés</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="px-4 py-2 border-b text-center"><%= order.id %></td>
            <td class="px-4 py-2 border-b text-center"><%= order.user.email %></td>
            <td class="px-4 py-2 border-b text-center"><%= number_to_currency(order.total_price, unit: '€') %></td>
            <td class="px-4 py-2 border-b text-center"><%= order.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            <td class="px-4 py-2 border-b text-center">
              <ul class="order-items list-disc pl-4">
                <% order.order_items.each do |order_item| %>
                  <li>
                    <%= order_item.quantity %> x <%= order_item.item.title %> :
                    <%= number_to_currency(order_item.unit_price, unit: '€') %>
                  </li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </article>
  <div class="text-center mt-4 mb-12 w-full">
    <a href="/dashboard" class="bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Retour au Dashboard</a>
  </div>
</section>

app/views/dashboard/products.html.erb
<div class="w-1/2 bg-gray-800 p-6 bg-black rounded-lg shadow-lg mt-32 mb-10 h-108 mx-auto">
  <h2 class="text-white text-xl text-center font-semibold mb-4">Liste des Produits en Boutique :</h2>

  <% @items.each_slice(4) do |item_group| %>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
      <% item_group.each do |item| %>
        <div class="relative bg-white rounded-lg overflow-hidden shadow-md">
          <img src="<%= item.image_url %>" alt="<%= item.alt %>" class="w-full h-32 object-cover object-center">
          <div class="px-4 py-3">
            <h3 class="text-black font-bold text-sm mb-2 text-center"><%= item.title %></h3>
            <p class="text-black text-xs text-center"><%= item.description %></p>
            <p class="text-black text-xs mt-5 text-center"><%= item.category %></p>

            <p class="text-black font-bold text-sm mt-2 text-center"><%= number_to_currency(item.price, unit: "€") %></p>
          </div>

          <%= link_to edit_item_path(item), class: "absolute bottom-0 left-0 mb-2 ml-2 text-blue-700 hover:text-blue-500", 'aria-label': "Éditer l'élément" do %>
            <i class="fas fa-edit"></i>
          <% end %>

          <%= form_for(item, url: item_path(item), method: :delete) do |f| %>
            <%= f.button type: 'submit', class: "absolute bottom-0 right-0 mb-2 mr-2 text-red-700 hover:text-red-500", 'aria-label': "Supprimer l'élément" do %>
              <i class="fas fa-trash"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="my-6"></div>
  <% end %>

  <div class="text-center">
    <a href="/dashboard" class="bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
      Retour au Dashboard
    </a>
  </div>
</div>

app/views/dashboard/quotes.html.erb
<section class="container mx-auto p-4">
  <div class="container mx-auto flex items-center justify-center mt-10">
    <h1 class="text-4xl font-bold p-4 border-4 border-gray-500 rounded inline-block">Liste des Devis : </h1>
  </div>
  <h2 class="text-xl font-semibold my-4">Devis Non traités :</h2>
  <article class="overflow-x-auto">
    <table class="min-w-full bg-gray-800 text-white border rounded-lg">
      <thead>
        <tr>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Prénom</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Nom</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Email</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Description</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Catégorie</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Devis traité</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Supprimer</th>
        </tr>
      </thead>
      <tbody>
        <% @unprocessed_quotes.each do |quote| %>
          <tr>
            <td class="px-4 py-2 border-b text-center"><%= quote.first_name %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.last_name %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.email %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.description %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.category %></td>
            <td class="px-4 py-2 border-b text-center">
              <%= form_with(url: mark_quote_path(quote), method: :post) do %>
                <%= hidden_field_tag :checked, true %>
                <%= submit_tag 'Marquer comme traité', class: 'bg-green-500 hover:bg-green-600 text-black font-bold py-2 px-4 rounded' %>
              <% end %>
            </td>
            <td class="px-4 py-2 border-b text-center">
              <%= form_for(quote, url: quote_path(quote), method: :delete, html: { class: 'delete-form' }) do |f| %>
                <%= f.button type: 'submit', class: 'text-red-700 hover:text-red-500', 'aria-label': 'Supprimer le devis' do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </article>
  <h2 class="text-xl font-semibold my-4">Devis traités :</h2>
  <article class="overflow-x-auto">
    <table class="min-w-full bg-gray-800 text-white border rounded-lg">
      <thead>
        <tr>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Prénom</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Nom</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Email</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Description</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Catégorie</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Re Traité</th>
          <th class="px-4 py-2 bg-purple-400 text-black border-b text-center">Supprimer</th>
        </tr>
      </thead>
      <tbody>
        <% @processed_quotes.each do |quote| %>
          <tr>
            <td class="px-4 py-2 border-b text-center"><%= quote.first_name %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.last_name %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.email %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.description %></td>
            <td class="px-4 py-2 border-b text-center"><%= quote.category %></td>
            <td class="px-4 py-2 border-b text-center">
              <%= form_with(url: reprocess_quote_path(quote), method: :post) do %>
                <%= submit_tag 'Retraiter Devis', class: 'bg-red-500 hover:bg-red-600 text-black font-bold py-2 px-4 rounded' %>
              <% end %>
            </td>
            <td class="px-4 py-2 border-b text-center">
              <%= form_for(quote, url: quote_path(quote), method: :delete, html: { class: 'delete-form' }) do |f| %>
                <%= f.button type: 'submit', class: 'text-red-700 hover:text-red-500' do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </article>
  <div class="text-center mt-4">
    <a href="/dashboard" class="bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Retour au Dashboard</a>
  </div>
</section>

app/views/dashboard/store.html.erb
<section class="max-w-screen-xl p-4 sm:p-6 mx-auto mt-20">
  <div class="flex justify-center">
    <div class="w-full sm:w-1/2 bg-gray-800 p-4 sm:p-6 rounded-lg shadow-lg mt-10">
      <%= form_for @item, url: dashboard_create_path, method: :post do |f| %>
        <div class="mb-3">
          <%= f.label :title, class: "text-sm font-bold text-white" %>
          <%= f.text_field :title, class: "bg-gray-700 border rounded w-full py-2 px-3 text-gray-100 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-3">
          <%= f.label :description, class: "text-sm font-bold text-white" %>
          <%= f.text_area :description, class: "bg-gray-700 border rounded w-full py-2 px-3 text-gray-100 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-3">
          <%= f.label :category, 'Catégorie de l\'élément', class: "text-sm font-bold text-white" %>
          <%= f.select :category, ['3D', 'Animation', 'Logo', 'Twitch', 'Merch', 'Tattoo', 'Illustrations', 'Avatars', 'Autres'], { prompt: 'Sélectionnez une catégorie' }, class: 'bg-gray-700 border rounded w-full py-2 px-3 text-gray-100 leading-tight focus:outline-none focus:shadow-outline' %>
        </div>

        <div class="mb-3">
          <%= f.label :price, class: "text-sm font-bold text-white" %>
          <%= f.number_field :price, step: "any", class: "bg-gray-700 border rounded w-full py-2 px-3 text-gray-100 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-3">
          <%= f.label :image_url, class: "text-sm font-bold text-white" %>
          <%= f.text_field :image_url, class: "bg-gray-700 border rounded w-full py-2 px-3 text-gray-100 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-3">
          <%= f.label :alt, class: "text-sm font-bold text-white" %>
          <%= f.text_field :alt, class: "bg-gray-700 border rounded w-full py-2 px-3 text-gray-100 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="text-center">
          <%= f.submit "Ajouter le produit", class: "bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
      <div class="text-center mt-4">
        <%= link_to "Retour au Dashboard", dashboard_path, class: "text-purple-400 hover:underline" %>
      </div>
    </div>
  </div>
</section>

app/views/dashboard/users.html.erb
<section class="container mx-auto mt-10">
  <h1 class="text-4xl font-bold p-4 border-4 border-gray-500 rounded mb-10 text-center">Liste des utilisateurs :</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
    <% @users.each do |user| %>
      <div class="bg-gray-800 shadow-md rounded-lg overflow-hidden">
        <div class="px-4 py-2">
          <p class="text-white"><%= user.email %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center mt-4">
    <a href="/dashboard" class="bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Retour au Dashboard</a>
  </div>
</section>