config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :cart_items, only: [:update]
  resources :order_items
  resources :orders
  resource :cart, only: [:show]

  resources :carts do
    delete 'cart_items/:cart_item_id', to: 'carts#destroy_item', on: :member, as: :delete_item
  end

  resources :items
  devise_for :users
 
  resources :users, :paths => 'users'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  resources :quotes, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :mark, action: :mark
      post :reprocess
    end
  end

  scope '/dashboard' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/users', to: 'dashboard#users', as: 'dashboard_users'
    get '/quotes', to: 'dashboard#quotes', as: 'dashboard_quotes'
    get '/store', to: 'dashboard#store', as: 'dashboard_store'
    post '/create', to: 'dashboard#create', as: 'dashboard_create'
    get '/products', to: 'dashboard#products', as: 'dashboard_products'
    get '/orders', to: 'dashboard#orders', as: 'dashboard_orders'
  end


  
  resources :orders, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  get 'welcome_email', to: 'welcome_mailer#welcome_email'
  get '/portfolio', to: 'portfolio#show', as: 'portfolio'
  get '/devis', to: 'quotes#new', as: 'devis'
  get 'faq', to: 'faq#index', as: 'faq'
  get '/mentions-legales', to: 'legal_notices#index', as: 'legal_notices'
  get '/politique-de-confidentialite', to: 'privacy_policy#index', as: 'privacy_policy'
  get '/politique-de-remboursement', to: 'refund_policy#index', as: 'refund_policy'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user  # Relation : Un panier (Cart) appartient à un utilisateur (User).
  has_many :cart_items, dependent: :destroy  # Relation : Un panier a de nombreux CartItems, et si le panier est supprimé, les CartItems associés sont également supprimés.
  has_many :items, through: :cart_items  # Relation : Un panier a de nombreux Items à travers les CartItems associés.

  # Méthode qui calcule le prix total de tous les éléments dans le panier.
  def total_price
    total = 0
    cart_items.each do |item|
      total += item.total_price
    end
    total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: %i[ show edit update destroy ]
  
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end
  
  # GET /carts/1 or /carts/1.json
  def show
    @user = current_user
    @cart = Cart.find_or_create_by(user: current_user)
    @cart_items = @cart.cart_items
    @cart_total = @cart.total_price
  end
  
  def get_cart_total
    @cart = current_user.cart
    @cart_total = @cart.total_price
  end
  
  
  # GET /carts/new
  def new
    @cart = Cart.new
  end
  
  # GET /carts/1/edit
  def edit
  end
  
  # POST /carts or /carts.json
  def create
    # Assurez-vous que l'utilisateur est connecté
    if user_signed_in?
      # Récupérez le panier de l'utilisateur actuel ou créez-en un s'il n'en a pas
      @cart = current_user.cart || current_user.create_cart
      
      # Récupérez l'élément à ajouter au panier
      @item = Item.find(params[:item_id]) # Assurez-vous que le paramètre :item_id est correctement passé
      
      # Utilisez directement params[:quantity] pour obtenir la quantité
      quantity = params[:quantity].to_i
      
      # Créez un nouvel élément dans le panier avec la quantité spécifiée
      @cart_item = @cart.cart_items.create(item: @item, quantity: quantity)
      
      # Redirigez l'utilisateur vers la page du panier
      redirect_to cart_path(@cart), notice: "L'élément a été ajouté au panier."
    else
      # Gérez le cas où l'utilisateur n'est pas connecté
      redirect_to items_path, alert: "Vous devez être connecté pour ajouter des articles au panier."
    end
  end
  
  
  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html do
          @cart.cart_items.each do |cart_item|
            cart_item.update(total_price: cart_item.quantity * cart_item.item.price)
          end
          redirect_to cart_url(@cart), notice: "Le panier a été mis à jour avec succès."
        end
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /carts/1 or /carts/1.json
  
  def destroy_item
    @cart = Cart.find(params[:id])
    @cart_item = @cart.cart_items.find(params[:cart_item_id])
    @cart_item.destroy
    
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: "L'article a été supprimé du panier avec succès." }
      format.json { head :no_content }
    end
  end
  
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = find_cart(params[:user_id], params[:cart_id])
  end
  
  # Only allow a list of trusted parameters through.
  def cart_params
    params.require(:cart).permit(:user_id)
  end
  
  
  def find_cart(user_id, cart_id)
    if user_id
      user = User.find(user_id)
      @cart = user.cart
    elsif cart_id
      @cart = Cart.find(cart_id)
    else
      # Gérer le cas où ni l'ID d'utilisateur ni l'ID de panier n'est présent
      # Par exemple, rediriger vers une page d'erreur ou effectuer une action appropriée.
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <p>
    <strong>User:</strong>
    <%= cart.user_id %>
  </p>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <aside style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </aside>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<section class="container mx-auto mt-10">
  <div class="flex flex-col-reverse sm:flex-row shadow-md my-10">
    <article class="w-full sm:w-3/4 bg-gray-800 px-4 py-4 sm:px-10 sm:py-10">
      <div class="flex justify-between border-b pb-4">
        <h1 class="font-semibold text-white text-xl sm:text-2xl">Votre Panier</h1>
        <h2 class="font-semibold text-white text-xl sm:text-2xl"><%= @cart_items.size %> Produits</h2>
      </div>
      <% if @cart_items.present? %>
        <div class="flex mt-4 mb-2 sm:mt-10 sm:mb-5">
          <h3 class="font-semibold text-white text-xs sm:text-sm uppercase w-2/5">Détails Produits</h3>
          <h3 class="font-semibold text-center text-white text-xs sm:text-sm uppercase w-1/5 sm:w-1/5 text-center">Prix</h3>
          <h3 class="font-semibold text-center text-white text-xs sm:text-sm uppercase w-1/5 sm:w-1/5 text-center">Quantité</h3>
          <h3 class="font-semibold text-center text-white text-xs sm:text-sm uppercase w-1/5 sm:w-1/5 text-center">Total</h3>
          <h3 class="font-semibold text-center text-white text-xs sm:text-sm uppercase w-1/5 sm:w-1/5 text-center">Supprimer</h3>
        </div>
        <% @cart_items.each do |cart_item| %>
          <div class="flex items-center -mx-2 px-2 sm:px-6 py-3 sm:py-5">
            <div class="flex w-2/5 sm:w-2/5">
              <div class="w-16 sm:w-20">
                <%= image_tag(cart_item.item.image_url, class: "h-16 sm:h-24") %>
              </div>
              <div class="flex flex-col justify-between ml-2 sm:ml-4 flex-grow">
                <span class="font-bold text-white text-xs sm:text-sm"><%= cart_item.item.title %></span>
              </div>
            </div>
            <span class="text-center w-1/5 sm:w-1/5 text-white font-semibold text-xs sm:text-sm"><%= number_to_currency(cart_item.item.price, unit: '€') %></span>
            <span class="text-center w-1/5 sm:w-1/5 text-white font-semibold text-xs sm:text-sm"><%= cart_item.quantity %></span>
            <span class="text-center w-1/5 sm:w-1/5 text-white font-semibold text-xs sm:text-sm"><%= number_to_currency(cart_item.quantity.to_i * cart_item.item.price, unit: '€') %></span>
            <div class="text-center w-1/5 sm:w-1/5">
              <%= button_to delete_item_cart_path(@cart, cart_item), method: :delete, class: "btn btn-danger text-white p-1" do %>
                <i class="fa-solid fa-trash text-red-800"></i>
              <% end %>
            </div>
          </div>
        <% end %>
        <a href="<%= items_path %>" class="flex font-semibold text-purple-400 text-xs sm:text-sm mt-4 sm:mt-10">
          <svg class="fill-current mr-2 text-purple-400 w-4 sm:w-5" viewBox="0 0 448 512">
            <path d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.090-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"/>
          </svg>
          Continuer le shopping
        </a>
      <% else %>
        <div class="empty-cart-message text-center text-red-600 text-2xl mt-4 sm:mt-10">
            Votre panier est vide.
            <%= link_to "Revenir à la liste", items_path, class: "text-purple-400 font-bold rounded-full underline text-xs sm:text-sm" %>
        </div>
      <% end %>
    </article>

    <article id="summary" class="w-full sm:w-1/4 bg-gray-600 px-4 py-4 sm:px-8 sm:py-10">
      <h1 class="font-semibold text-white text-xl sm:text-2xl border-b pb-4">Récapitulatif</h1>
      <div class="flex justify-between mt-4 sm:mt-10 mb-2 sm:mb-5">
          <span class="font-semibold text-white text-xs sm:text-sm uppercase">Produits <%= @cart_items.size %></span>
          <span class="font-semibold text-white text-xs sm:text-sm"><%= number_to_currency(@cart_items.sum { |item| item.quantity.to_i * item.item.price }, unit: '€') %></span>
      </div>
      <div class="py-6 sm:py-10">
        <label for="promo" class="font-semibold text-white inline-block mb-3 text-xs sm:text-sm uppercase">Code Promo</label>
        <input type="text" id="promo" placeholder="! FONCTION A VENIR !" class="p-2 text-xs sm:text-sm w-full pointer-events-none" disabled>
      </div>
      <button class="bg-red-500 hover:bg-red-600 px-4 sm:px-5 py-2 text-xs sm:text-sm text-white uppercase pointer-events-none" disabled>Appliquer</button>
      <div class="border-t mt-4 sm:mt-8">
        <div class="flex font-semibold text-white justify-between py-3 text-xs sm:text-sm uppercase">
          <span>Total Commande</span>
          <span><%= number_to_currency(@cart_items.sum { |item| item.quantity.to_i * item.item.price }, unit: '€') %></span>
        </div>
        <% if @cart_items.sum { |item| item.quantity.to_i * item.item.price } > 0 %>
          <%= button_to "Payer", checkout_create_path(total: @cart_total), class: "bg-purple-400 font-semibold hover:bg-purple-300 py-2 text-xs sm:text-sm text-black uppercase w-full btn btn-primary", data: {turbo: false} %>
        <% else %>
          <%= button_to "Payer", "#", class: "bg-purple-400 font-semibold py-2 text-xs sm:text-sm text-black uppercase w-full btn btn-primary disabled", disabled: true %>
        <% end %>
      </div> 
    </article>
  </div>
</section>