config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :cart_items, only: [:update]
  resources :order_items
  resources :orders
  resource :cart, only: [:show]

  resources :carts do
    delete 'cart_items/:cart_item_id', to: 'carts#destroy_item', on: :member, as: :delete_item
  end

  resources :items
  devise_for :users
 
  resources :users, :paths => 'users'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  resources :quotes, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :mark, action: :mark
      post :reprocess
    end
  end

  scope '/dashboard' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/users', to: 'dashboard#users', as: 'dashboard_users'
    get '/quotes', to: 'dashboard#quotes', as: 'dashboard_quotes'
    get '/store', to: 'dashboard#store', as: 'dashboard_store'
    post '/create', to: 'dashboard#create', as: 'dashboard_create'
    get '/products', to: 'dashboard#products', as: 'dashboard_products'
    get '/orders', to: 'dashboard#orders', as: 'dashboard_orders'
  end


  
  resources :orders, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  get 'welcome_email', to: 'welcome_mailer#welcome_email'
  get '/portfolio', to: 'portfolio#show', as: 'portfolio'
  get '/devis', to: 'quotes#new', as: 'devis'
  get 'faq', to: 'faq#index', as: 'faq'
  get '/mentions-legales', to: 'legal_notices#index', as: 'legal_notices'
  get '/politique-de-confidentialite', to: 'privacy_policy#index', as: 'privacy_policy'
  get '/politique-de-remboursement', to: 'refund_policy#index', as: 'refund_policy'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart  # Relation : Un CartItem appartient à un Cart.
  belongs_to :item  # Relation : Un CartItem appartient à un Item.

  # Méthode qui calcule le prix total pour cet élément du panier.
  def total_price
    quantity * item.price  # La quantité de l'élément multipliée par le prix unitaire de l'Item.
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: %i[ show edit update destroy ]
  
  # GET /cart_items or /cart_items.json
  def index
    @cart_items = CartItem.all
  end
  
  # GET /cart_items/1 or /cart_items/1.json
  def show
  end
  
  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end
  
  # GET /cart_items/1/edit
  def edit
  end
  
  # POST /cart_items or /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)
    
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to cart_path(current_user.cart), notice: "L'article du panier a été créé avec succès." }
        format.json { render :show, status: :created, location: current_user.cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /cart_items/1 or /cart_items/1.json
  def update
    
    respond_to do |format|
      if @cart_item.update!(cart_item_params)
        format.html { redirect_to cart_url(current_user.cart), notice: "Le panier a été mis à jour avec succès."}           
        format.json { render :show, status: :ok, location: current_user.cart }
      end
    end
  end
  # DELETE /cart_items/1 or /cart_items/1.json
  def destroy
    @cart_item.destroy
    
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: "L'article du panier a été détruit avec succès." }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end
  
  # Only allow a list of trusted parameters through.
  def cart_item_params
    params.require(:cart_item).permit(:cart_id, :item_id, :quantity)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item.html.erb
<article id="<%= dom_id cart_item %>">
  <p>
    <strong>Cart:</strong>
    <%= cart_item.cart_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= cart_item.item_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= cart_item.quantity %>
  </p>
</article>

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item) do |form| %>
  <% if cart_item.errors.any? %>
    <article style="color: red">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>
      <ul>
        <% cart_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </article>
  <% end %>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing cart item</h1>

<%= render "form", cart_item: @cart_item %>

<br>

<div>
  <%= link_to "Show this cart item", @cart_item %> |
  <%= link_to "Back to cart items", cart_items_path %>
</div>

app/views/cart_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cart items</h1>

<div id="cart_items">
  <% @cart_items.each do |cart_item| %>
    <%= render cart_item %>
    <p>
      <%= link_to "Show this cart item", cart_item %>
    </p>
  <% end %>
</div>

<%= link_to "New cart item", new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart item</h1>

<%= render "form", cart_item: @cart_item %>

<br>

<div>
  <%= link_to "Back to cart items", cart_items_path %>
</div>

app/views/cart_items/show.html.erb
<form action="<%= cart_item_path(@cart_item) %>" method="post">
</form>