config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :cart_items, only: [:update]
  resources :order_items
  resources :orders
  resource :cart, only: [:show]

  resources :carts do
    delete 'cart_items/:cart_item_id', to: 'carts#destroy_item', on: :member, as: :delete_item
  end

  resources :items
  devise_for :users
 
  resources :users, :paths => 'users'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  resources :quotes, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :mark, action: :mark
      post :reprocess
    end
  end

  scope '/dashboard' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/users', to: 'dashboard#users', as: 'dashboard_users'
    get '/quotes', to: 'dashboard#quotes', as: 'dashboard_quotes'
    get '/store', to: 'dashboard#store', as: 'dashboard_store'
    post '/create', to: 'dashboard#create', as: 'dashboard_create'
    get '/products', to: 'dashboard#products', as: 'dashboard_products'
    get '/orders', to: 'dashboard#orders', as: 'dashboard_orders'
  end


  
  resources :orders, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  get 'welcome_email', to: 'welcome_mailer#welcome_email'
  get '/portfolio', to: 'portfolio#show', as: 'portfolio'
  get '/devis', to: 'quotes#new', as: 'devis'
  get 'faq', to: 'faq#index', as: 'faq'
  get '/mentions-legales', to: 'legal_notices#index', as: 'legal_notices'
  get '/politique-de-confidentialite', to: 'privacy_policy#index', as: 'privacy_policy'
  get '/politique-de-remboursement', to: 'refund_policy#index', as: 'refund_policy'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/item.rb
class Item < ApplicationRecord
    # Validation : Assurez-vous que le titre est présent.
    validates :title, presence: true
    # Validation : Assurez-vous que la description est présente.
    validates :description, presence: true
    # Validation : Assurez-vous que le prix est présent.
    validates :price, presence: true
    # Validation : Assurez-vous que l'URL de l'image est présente et unique.
    validates :image_url, presence: true, uniqueness: true
    # Validation : Assurez-vous que le texte alternatif (alt) est présent.
    validates :alt, presence: true
    # Validation : Assurez-vous que la catégorie est présente.
    validates :category, presence: true
  
    # Relation : Un Item peut être présent dans de nombreux paniers (CartItems).
    has_many :cart_items, dependent: :destroy
    # Relation : Un Item peut être présent dans de nombreux éléments de commande (OrderItems).
    has_many :order_items
    # Relation : Si l'Item est supprimé, supprimez également tous les OrderItems associés.
    has_many :order_items, dependent: :destroy
  
    # Options de catégorie disponibles pour les Items.
    CATEGORY_OPTIONS = ['3D', 'Animation', 'Logo', 'Twitch', 'Merch', 'Tattoo', 'Illustrations', 'Avatars', 'Autres']
  
    # Utilisation d'une énumération pour gérer la catégorie.
    enum category_enum: CATEGORY_OPTIONS
  end
  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  
  #La def destroy et create et edit concerne le coté admin qui peut avoir la gestion des items 
  def destroy
    @item.destroy
    redirect_to dashboard_products_path, notice: "L'objet a été détruit avec succès."
  end
  
  # GET /items or /items.json
  def index
    @items = Item.all
  end
  
  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end
  
  # GET /items/new
  def new
    @item = Item.new
  end
  
  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    @categories = Item.distinct.pluck(:category)
  end
  
  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "L'élément a été créé avec succès." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /items/1 or /items/1.json
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to dashboard_products_path, notice: "Article mis à jour avec succès."
    else
      render :edit
    end
  end
  
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end
  
  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:title, :description, :price, :image, :alt, :category)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :alt, style: "display: block" %>
    <%= form.text_field :alt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<section id="<%= dom_id item %>">
  <p>
    <strong>Title:</strong>
    <%= item.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= item.image %>
  </p>

  <p>
    <strong>Alt:</strong>
    <%= item.alt %>
  </p>
</section>

app/views/items/edit.html.erb
<section class="w-1/2 bg-gray-800 p-6 rounded-lg shadow-lg mt-10 mb-10 h-108 mx-auto">
  <h2 class="text-white text-xl text-center font-semibold mb-4">Édition d'un Article</h2>
  <%= form_for(@item, url: item_path(@item), method: :patch) do |f| %>
    <div class="grid grid-cols-1 gap-4">
      <div class="relative bg-gray-400 rounded-lg overflow-hidden shadow-md">
        <img src="<%= @item.image_url %>" alt="<%= @item.alt %>" class="w-full h-32 object-cover object-center">
        <div class="px-4 py-3">
          <%= f.label :title, class: "text-black font-bold text-sm mb-2" %>
          <%= f.text_field :title, class: "w-full bg-gray-200 rounded-lg" %>

          <%= f.label :description, class: "text-black text-xs mt-3" %>
          <%= f.text_area :description, class: "w-full bg-gray-200 rounded-lg" %>

          <%= f.label :category, class: "text-black text-xs mt-3" %>
          <%= f.select :category, @categories.map { |c| [c, c] }, { selected: @item.category }, { class: "w-full bg-gray-200 rounded-lg" } %>

          <%= f.label :price, class: "text-black font-bold text-sm mt-3" %>
          <%= f.number_field :price, class: "w-full bg-gray-200 rounded-lg" %>
        </div>
      </div>
    </div>
    <div class="my-6"></div>
    
    <div class="text-center">
      <%= f.submit "Enregistrer les modifications", class: "bg-purple-400 hover:bg-purple-300 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</section>

app/views/items/index.html.erb
<div class="container mx-auto text-center mt-10 sm:mt-20 mb-4 sm:mb-10">
  <h1 class="text-2xl sm:text-4xl font-bold p-2 sm:p-4 border-4 border-gray-500 rounded inline-block">Boutique RustOff</h1>
</div>

<section class="info-wrapper mb-4 sm:mb-10 flex justify-center">
  <article class="shipping-container flex items-center">
    <i class="fas fa-truck text-gray-800 text-xl sm:text-2xl mr-2"></i>
    <div class="info-desc text-sm sm:text-base">Livraison Rapide</div>
  </article>
  <article class="inventory-container flex items-center ml-4 sm:ml-8">
    <i class="fas fa-shopping-basket text-gray-800 text-xl sm:text-2xl mr-2"></i>
    <div class="info-desc text-sm sm:text-base">Large Choix</div>
  </article>
</section>

<section class="main-wrapper text-white flex flex-col-reverse sm:flex-row sm:items-start">
  <article class="menu">
    <div class="menu-item All">
      <div class="menu-item-title">All</div>
    </div>
    <div class='menu-item Animation' id='Animation'>
      <div class='menu-item-title'>Animation</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Logo' id='Logo'>
      <div class='menu-item-title'>Logo</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item 3D' id='3D'>
      <div class='menu-item-title'>3D</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Merch' id='Merch'>
      <div class='menu-item-title'>Merch</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Tattoo' id='Tattoo'>
      <div class='menu-item-title'>Tattoo</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Illustrations' id='Illustrations'>
      <div class='menu-item-title'>Illustrations</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Avatars' id='Avatars'>
      <div class='menu-item-title'>Avatars</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Autres' id='Autres'>
      <div class='menu-item-title'>Autres</div>
      <div class='menu-item-number'></div>
    </div>
    <div class='menu-item Twitch' id='Twitch'>
      <div class='menu-item-title'>Twitch</div>
      <div class='menu-item-number'></div>
    </div>
  </article>


  <article class="products-container flex flex-wrap w-full ml-0 sm:ml-4" id="products-container">
    <% @items.each do |item| %>
      <div class="relative bg-gray-800 rounded-lg overflow-hidden shadow-md shop-card w-full sm:w-72 mx-2 my-4 min-h-card" data-cat="<%= item.category %>">
        <img src="<%= item.image_url %>" alt="<%= item.alt %>" class="w-full h-48 object-cover object-center">
        <div class="px-2 sm:px-4 py-2 sm:py-3">
          <h1 class="text-white font-bold text-base sm:text-sm mb-1 sm:mb-2 text-center"><%= item.title %></h1>
          <p class="text-white text-xs sm:text-sm text-center"><%= item.description %></p>
          <p class="text-green-500 font-bold text-sm sm:text-base mt-1 sm:mt-2 text-center"><%= number_to_currency(item.price, unit: "€") %></p>
        </div>
          <a href="<%= item_path(item) %>" class="absolute bottom-0 right-0 mb-1 sm:mb-2 mr-1 sm:mr-2 bg-gradient-to-r from-purple-300 to-purple-600 text-black text-xs sm:text-sm font-bold py-1 px-2 sm:px-3 rounded-lg hover:scale-105 duration-200 hover:text-black hover:border-gray-800 hover:from-purple-600 hover:to-purple-300">
            Voir
          </a>
      </div>
    <% end %>
  </article>
</section>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<section class="p-2">
  <div class="rounded-lg shadow-md overflow-hidden bg-gray-800 mt-4 mb-4 mx-2">
    <%= image_tag @item.image_url, alt: @item.title, class: "w-full h-auto" %>
    <div class="p-3">
      <h2 class="text-md sm:text-lg md:text-xl lg:text-2xl xl:text-3xl text-white font-semibold mb-2"><%= @item.title %></h2>
      <p class="text-white mb-2 text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl"><%= @item.description %></p>
      <p class="text-green-500 font-semibold text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl">€<%= @item.price %></p>
      <div class="mt-2">
        <%= form_tag({ controller: "carts", action: "create" }, method: :post, class: "flex items-center") do %>
          <%= hidden_field_tag "item_id", @item.id %>
          <label for="quantity" class="text-white font-semibold text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl mr-2">Quantité:</label>
          <%= number_field_tag "quantity", 1, min: 1, class: "w-12 text-center border rounded-md text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl", id: "quantity" %>
          <%= submit_tag 'Ajouter au panier', class: 'bg-gradient-to-r from-purple-300 to-purple-600 text-black font-semibold px-4 py-2 rounded-lg border border-gray-600 hover:scale-105 duration-200 hover:text-black hover:border-gray-800 hover:from-purple-600 hover:to-purple-300 ml-2 text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl' %>
        <% end %>
        <%= link_to "Revenir à la liste", items_path, class: "bg-custom-color hover:bg-gray-400 text-white font-semibold py-1 px-2 rounded-full text-xxs sm:text-xs md:text-sm lg:text-base xl:text-lg" %>
      </div>
    </div>
  </div>
</section>